#配置默认端口
server:
  port: 8080

#日志配置
# 不指定路径，在当前项目下生成 srpingboot.log
# 指定路径，在路径下生成
logging:
  level:
    #    root: debug
    org.springframework.security: debug #打印security日志记录
#  file:
#    name: SrpingBoot.log

#数据库连接 服务器
spring:
  datasource:
      username: root
      password: zmf123456
      url: jdbc:mysql://106.52.174.153:3306/dati?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8
      driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: '077054'
#    url: jdbc:mysql://127.0.0.1:3306/beifen?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8
#    driver-class-name: com.mysql.cj.jdbc.Driver
  # JPA 相关配置
  jpa:
    hibernate:
      ddl-auto: none  # update  更新 或 create 创建数据表   none 不操作
    show-sql: true  #控制台显示SQL
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    #database-platform: org.hibernate.dialect.SQLServer2008Dialect
    properties:
      hibernate.current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
  # 允许预检请求
  mvc:
    dispatch-options-request: true
    ##########################################
    ####yan   url路径
    static-path-pattern: /image/**

  ####yan    绑定的储存地址
  resources:
    static-locations: file:E:/upImages/noticethumbnail
    ################################################
  #上传限制文件大小
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 50MB


  #system自定义配置项
  jackson:
    date-format=yyyy-MM-dd HH:mm:ss

system:
  path:
    #文件上传根目录 设置
    upload: E://upFiles
    #webapp文件路径
    webapp: E://webapp

    #图片上传路径
    uploadImage: E:/upImages/noticethumbnail

    #图片真实路径
    imageRealPath: E:/develoment/tomcat/apache-tomcat-8.5.63/webapps/upImages/noticethumbnail
    #imageRealPath: E:\apache-tomcat-8.5.33-server\webapps\upImages\noticethumbnail

ureport:
  prefix: sqlserver-
  disabled: false
  fileStoreDir: E:/ureportfiles
  #fileStoreDir: /WEB-INF/ureportfiles/
  #ureport配置
  disableHttpSessionReportCache: false
  # 将ureport.disableFileProvider改成true,即可禁用默认提供的文件存储机制
  disableFileProvider: true
  debug: true
